const ADD_GROUP = "ADD_GROUPS";
const DELETE_GROUP = "DELETE_GROUPS";
const SET_GROUP_TITLE = "SET_GROUP_TITLE";
const ADD_TASK = "ADD_TASK";
const DELETE_TASK = "DELETE_TASK";
const SET_TITLE_TASK = "SET_TITLE_TASK";
const SET_DESCRIPTION_TASK = "SET_DESCRIPTION_TASK";

export {
    ADD_GROUP,
    DELETE_GROUP,
    SET_GROUP_TITLE,
    ADD_TASK,
    DELETE_TASK,
    SET_TITLE_TASK,
    SET_DESCRIPTION_TASK,
};
